# Generated by Django 6.0.6 on 2026-06-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customers",
            new_name="Customer",
        ),
    ]
