# Generated by Django 6.0.6 on 2026-06-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customers_name", models.CharField(max_length=200)),
                ("customers_email", models.EmailField(max_length=254, unique=True)),
                ("customers_phone", models.CharField(max_length=20)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
